# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49de8c3779298a17a9b877ed427b780a68458e1878256f9cd574c5a39433607e419c7ac3e9423a5d38b6c1c1c85bccfba3b5d5777a35abe8f66f1b68b5739cc3

test:
  secret_key_base: d0f8d26f788d4488aa85b181aa7896b1a41aef3db5a42d926451bb392e0318b2471d3c12e4e649ecafb8cc9b1ebf2824000d651c39bcd58ea12dd2068fcf9bc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
